name: build

on:
  push:
    branches:
      - react

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Building the app
        with:
          CI: ''            # disable CRA’s CI mode so lint‐warnings aren’t fatal
        run: npm start

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages